"""
export_excel.py

Produces a multi-sheet Excel workbook from the breakdown DataFrames, as the
downloadable artifact for the portfolio (mirrors the original tool's
multi-tab output, but generated by Python instead of Apps Script).
"""

from pathlib import Path
import pandas as pd

OUTPUT_DIR = Path(__file__).parent / "output"


def export_to_excel(breakdowns: dict[str, pd.DataFrame],
                     engagement_summary: pd.DataFrame,
                     engagement_by_class: pd.DataFrame,
                     filename: str = "event_attendance_analysis_SYNTHETIC.xlsx") -> Path:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUTPUT_DIR / filename

    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        # Cover/notice sheet first
        notice = pd.DataFrame({
            "NOTICE": [
                "All data in this workbook is SYNTHETICALLY GENERATED.",
                "No real student records, IDs, or attendance data are used.",
                "This workbook demonstrates the output format of a Python-based",
                "rebuild of an institutional attendance/engagement reporting tool",
                "originally built in Google Apps Script.",
            ]
        })
        notice.to_excel(writer, sheet_name="README", index=False)

        for sheet_name, df in breakdowns.items():
            safe_name = sheet_name[:31]  # Excel sheet name limit
            df.to_excel(writer, sheet_name=safe_name, index=False)

        engagement_summary.to_excel(writer, sheet_name="Engagement Summary", index=False)
        engagement_by_class.to_excel(writer, sheet_name="Engagement by Class", index=False)

    print(f"Wrote Excel workbook: {path}")
    return path
